export const Books = [
    {
        id: 1,
        title: 'Never Lie',
        author: 'Freida McFadden',
        publishedDate: 2022,
        category: "Fiction",
        description: "Never Lie is the perfect thrill ride of a novel! I was pulled into the story right from the start and read breathlessly until the shocking conclusion.",
        coverImage: "https://m.media-amazon.com/images/I/8196x-1wIOL._SY342_.jpg",
        ratings: 4.7,
    },

    {
        id: 2,
        title: 'The Locked Door',
        author: 'Freida McFadden',
        publishedDate: 2021,
        category: "Fiction",
        description: "While eleven-year-old Nora Davis was up in her bedroom doing homework, she had no idea her father was killing women in the basement.Until the day the police arrived at their front door",
        coverImage: "https://m.media-amazon.com/images/I/41KTgPk0GzL._SY445_SX342_.jpg",
        ratings: 4.8,
    },
 
    {
        id: 3,
        title: 'Little Women',
        author: ' LouisaMay Alcott',
        publishedDate: 2012,
        category: "Classic",
        description: "Christmas won't be the same this year for Meg, Jo, Beth and Amy, as their father is away fighting in the Civil War, and the family has fallen on hard times.",
        coverImage: "https://m.media-amazon.com/images/I/91ORJa-xI9L._SY342_.jpg",
        ratings: 4.3,
    },

    {
        id: 4,
        title: 'Metamorphosis',
        author: 'Franz Kafka',
        publishedDate: 2014,
        category: "Classic",
        description: "A classic novel about Metamorphosis transformed.",
        coverImage: "https://m.media-amazon.com/images/I/71qR+kG+43L._SY342_.jpg",
        ratings: 4.4,
    },

    {
        id: 5,
        title: 'Ghosts of The Silent Hills',
        author: 'Anita Krishan',
        publishedDate: 2019,
        category: "Mystery",
        description: "The dead do not rest till they get what they want. You have arrived in the hills. In here, you are surrounded by dense, menacing forests, enveloped in a deadly silence",
        coverImage: "https://m.media-amazon.com/images/I/71NUqTiGrOL._SY342_.jpg",
        ratings: 4.3,
    },

    {
        id: 6,
        title: 'The Designer',
        author: 'Paul Haedo',
        publishedDate: 2021,
        category: "Sci-Fi",
        description: "For millions of years, the ark flotilla wandered through inter-galactic space until it reached a new galaxy, and eventually, a new world.",
        coverImage: "https://m.media-amazon.com/images/I/7151zO-pJ7L._SY466_.jpg",
        ratings: 3.7,
    },

    {
        id: 7,
        title: 'One Of Us Is Lying',
        author: 'Karen McManus',
        publishedDate: 2000,
        category: "Mystery",
        description: "Twisty plotting, breakneck pacing and intriguing characterisation add up to an exciting single-sitting thrillerish treat. A fantastic murder mystery, packed with cryptic clues and countless plot twists. I could not put this book down ",
        coverImage: "https://marketplace.canva.com/EAFf0E5urqk/1/0/1003w/canva-blue-and-green-surreal-fiction-book-cover-53S3IzrNxvY.jpg",
        ratings: 4.4,
    },

    {
        id: 8,
        title: 'That Night: Four Friends, Twenty Years',
        author: 'Nidhi Upadhyay',
        publishedDate: 2021,
        category: "Mystery",
        description: "It was the night that began with a bottle of whisky and a game of Ouija but ended with the death of Sania, their unlikeable hostel mate. The friends vowed never to discuss that fateful night, a pact that had kept their friendship and guilt dormant for the last twenty years",
        coverImage: "https://m.media-amazon.com/images/I/81b1PP4RK1L._SY342_.jpg",
        ratings: 4.1,
    },

    {
        id: 9,
        title: 'YOU ONLY LIVE ONCE',
        author: 'STUTI CHANGLE',
        publishedDate: 2020,
        category: "Fiction",
        description: "Find the answers about your own life in this story about searching for love and discovering yourself. Join a broken but rising YouTube star Alara, a struggling but hopeful stand-up comedian Aarav, and a zany but zen beach shack owner Ricky.",
        coverImage: "https://m.media-amazon.com/images/I/71dNsRuYL7L._SY466_.jpg",
        ratings: 5.0,
    },

    {
        id: 10,
        title: 'Alien - Out of the Shadows',
        author: 'Tim Lebbon',
        publishedDate: 2024,
        category: "Sci-Fi",
        description: "Featuring the iconic Ellen Ripley in a terrifying new adventure that bridges the gap between Alien and Aliens. Officially sanctioned and true to the Alien canon, Alien: Out of the Shadows expands upon the well-loved mythos and is a must for all Alien fans.",
        coverImage: "https://m.media-amazon.com/images/I/41lIOeBoW3L._SY445_SX342_.jpg",
        ratings: 4.2,
    },

    {
        id: 11,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        publishedDate: 1960,
        category: "Classic",
        description: "A classic novel depicting racial injustice in the American South.",
        coverImage: "https://m.media-amazon.com/images/I/51c3anbwfqL._SY445_SX342_.jpg",
        ratings: 4.2,
    },
    {
        id: 12,
        title: "1984",
        author: "George Orwell",
        publishedDate: 1949,
        category: "Sci-Fi",
        description: "A dystopian novel portraying a totalitarian society.",
        coverImage: "https://m.media-amazon.com/images/I/51BIA4rraeL._AC_UF1000,1000_QL80_.jpg",
        ratings: 4.9,
    },
    {
        id: 13,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        publishedDate: 1925,
        category: "Classic",
        description: "A tale of the American Dream, wealth, and love during the Roaring Twenties.",
        coverImage: "https://m.media-amazon.com/images/I/817+192hZyS._SY342_.jpg",
        ratings: 4.3,
    },
    {
        id: 14,
        title: "THE SILENT PATIENT",
        author: " Alex Michaelides",
        publishedDate: 2019,
        category: "Fiction",
        description: "Masterly plotting, Hitchcockian suspense and an absolute jaw-dropper of an ending.",
        coverImage: "https://m.media-amazon.com/images/I/81y9uCHoxrL._SY342_.jpg",
        ratings: 3.7,
    },
    {
        id: 15,
        title: "The Space Trilogy",
        author: "C. S. Lewis",
        publishedDate: 2022,
        category: "Sci-Fi",
        description: "The Space Trilogy is a fantastic work of fantasy that demonstrates C.S.Lewis's incredible imagination. This new one-volume version commemorates the 75th anniversary of Out of the Silent Planet's first publication with an exclusive Foreword by J.R.R. Tolkien, who inspired the main character of Ransom.",
        coverImage: "https://m.media-amazon.com/images/I/71gzD+QgoOL._SY342_.jpg",
        ratings: 4.5,
    },
    {
        id: 16,
        title: "The Wind on the Haunted Hill",
        author: "Ruskin Bond",
        publishedDate: 2018,
        category: "Mystery",
        description: "This book is about a haunted hill and there wind flow in sometime cold and sometime is hot.",
        coverImage: "https://m.media-amazon.com/images/I/91TBcPLZqJL._SY342_.jpg",
        ratings: 4.2,
    }
];